# Generated by Django 6.0.4 on 2026-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderitem_created_at_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='booked_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
