# Generated by Django 6.0.4 on 2026-04-19 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=20)),
                ('citizen', models.CharField(max_length=30)),
                ('citizenfront', models.ImageField(blank=True, null=True, upload_to='Id')),
                ('citizenback', models.ImageField(blank=True, null=True, upload_to='Id')),
                ('licence', models.IntegerField(blank=True, max_length=30, null=True)),
                ('licencefront', models.ImageField(blank=True, null=True, upload_to='Id')),
                ('licenceback', models.ImageField(blank=True, null=True, upload_to='Id')),
                ('approved', models.BooleanField(default=False)),
                ('account_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
