# Generated by Django 6.0.4 on 2026-04-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='licence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
