# Generated by Django 6.0.4 on 2026-04-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='heroproduct',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
