# Generated by Django 6.0.4 on 2026-04-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_product_productimage_review_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
