# Generated by Django 6.0.4 on 2026-04-20 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_make'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bimg_detail',
            field=models.ImageField(blank=True, null=True, upload_to='bluebook'),
        ),
        migrations.AddField(
            model_name='product',
            name='bimg_number',
            field=models.ImageField(blank=True, null=True, upload_to='bluebook'),
        ),
        migrations.AddField(
            model_name='product',
            name='bimg_owner',
            field=models.ImageField(blank=True, null=True, upload_to='bluebook'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='plate',
            field=models.CharField(default='1111', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='plate_img',
            field=models.ImageField(blank=True, null=True, upload_to='plate'),
        ),
    ]
