# Generated by Django 6.0.4 on 2026-04-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_bimg_detail_product_bimg_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='plate_img',
        ),
    ]
